# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Centauri/v585/v585.cache/wt [current_project]
set_property parent.project_path C:/Users/Centauri/v585/v585.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_mem {
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/boot/boot-4.mem
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/boot/boot-3.mem
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/boot/boot-1.mem
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/boot/boot-2.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_nand3.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_or4.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_nand2.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_reg.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_ha2.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_and3.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_and4.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_and2.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_or2.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_reg_set.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_ao3.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_ao4.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_inv.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_nor4.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_mux2.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_nao4.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_nor2.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_mux4.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_xor2.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_fa2.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/notech/notech_nao3.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/psram_clk_iob.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/psram_wait_iob.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/acu.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/cacheram.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/synthetic_op.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/psram_data_iob.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/datacache.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/psram_off_iob.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/psram_ctrlr.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/uart_16750.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/psram_sync.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/extrom.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/v586.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/asram_core.v
  C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/TOP_SYS.v
}
read_vhdl -library xil_defaultlib C:/Users/Centauri/v585/v585.srcs/sources_1/imports/trunk/rtl/clk_wiz_v3_6.vhd
read_xdc C:/Users/Centauri/v585/v585.srcs/constrs_1/imports/xdc/TOP_SYS.xdc
set_property used_in_implementation false [get_files C:/Users/Centauri/v585/v585.srcs/constrs_1/imports/xdc/TOP_SYS.xdc]

synth_design -top TOP_SYS -part xc7a100tcsg324-3
write_checkpoint -noxdef TOP_SYS.dcp
catch { report_utilization -file TOP_SYS_utilization_synth.rpt -pb TOP_SYS_utilization_synth.pb }
